---
- hosts: localhost
  connection: local
  gather_facts: no
  become: false
  tasks:
    - replace:
        dest: inventory/aws/hosts/ec2.ini
        regexp: "^# instance_filters = tag:env=staging"
        replace: "instance_filters = tag:env={{ cluster_id }}"
    - replace:
        dest: inventory/aws/hosts/ec2.ini
        regexp: "^instance_filters = tag:env=(.*)"
        replace: "instance_filters = tag:env={{ cluster_id }}"
    - file:
        path: inventory/static
        state: directory

- hosts: localhost
  connection: local
  gather_facts: no
  become: false
  roles:
    - rhtps.private-aws
  tags:
    - infrastructure_deploy

- hosts: tag_instance_role_gluster_node
  connection: ssh
  gather_facts: yes
  become: true
  pre_tasks:
    - meta: refresh_inventory
  roles:
    - gluster-install
