- block:
    - name: apply the "{{ io_profile }}" tuned profile
      shell: tuned-adm profile "rhgs-{{ io_profile }}-io"

    - name: ensure EPEL is installed
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: installed

    - name: install the Phoronix Test Suite
      yum:
        name: phoronix-test-suite
        state: latest
        enablerepo: epel
  tags:
    - perf_harness